apiVersion: batch/v2alpha1 
kind: CronJob
metadata:
  name: backup
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "*/1 * * * *"  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobbackup"
        spec:
          containers:
          - name: backup
            image: "docker-registry.default.svc:5000/waiverdb-backup/waiverdb-backup:latest"
            command: ['/bin/bash', '-c', 'pg_dump -d waiverdb -h waiverdb-test-123-database -p 5432 -U waiverdb -f /var/tmp/waiverdb-backups/$(date +"%Y-%m-%d-%H:%M:%S,%3N") && ls -la /var/tmp/waiverdb-backups && cat /etc/passwd && sleep 60']
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: waiverdb-test-123-secret
                  key: database-password
          restartPolicy: OnFailure 
