apiVersion: v1 
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/5 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobbackup"
        spec:
          containers:
          - name: backup
            image: waiverdb-backup
            command: ['pg_dump', '-d', 'waiverdb', '-h', 'waiverdb-test-123-database', '-p', '5432', '-U', 'waiverdb', '>', 'waiverdb-backups/$(date +"%Y-%m-%d-%H:%M:%S,%3N")']
          restartPolicy: OnFailure 
