apiVersion: batch/v2alpha1 
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/5 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobbackup"
        spec:
          containers:
          - env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: waiverdb-test-123-secret
                  key: database-password
          - name: backup
            image: "docker-registry.default.svc:5000/waiverdb-backup/waiverdb-backup:latest"
            command: ['pg_dump', '-d', 'waiverdb', '-h', 'waiverdb-test-123-database', '-p', '5432', '-U', 'waiverdb', '-f', 'waiverdb-backups/$(date +"%Y-%m-%d-%H:%M:%S,%3N")']
          restartPolicy: OnFailure 
