apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: backup-test
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: backup-agent
---
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: waiverdb-backup
      service: backup
    name: waiverdb-backup
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: waiverdb-backup
      deploymentconfig: waiverdb-backup
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: waiverdb-backup
          deploymentconfig: waiverdb-backup
      spec:
        containers:
        - env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: waiverdb-test-123-secret 
                key: database-password
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - waiverdb-backup
        from:
          kind: ImageStreamTag
          name: waiverdb-backup:latest
          namespace: waiverdb-backup 
      type: ImageChange
---
apiVersion: v1 
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/5 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobbackup"
          - name: backup
            command: ['pg_dump', '-d', 'waiverdb', '-h', 'waiverdb-test-123-database', '-p', '5432', '-U', 'waiverdb', '>', 'waiverdb-backups/$(date +"%Y-%m-%d-%H:%M:%S,%3N")']
          restartPolicy: OnFailure 
